---
# === CRT === #
domain: yourbestdomain.com
passphrase: # Set if you want passphrase
country_name: RU
state_or_province: RU
locality_name: Moscow
email_address: admin@yourbestdomain.com
organization_name: Test Company LLC
# === Private Key === #
key_size: 2048
key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
